spring.application.name=CRUD_Bvpm

spring.datasource.url=jdbc:mysql://localhost:3306/crud_bvpm
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
# Ordena los endpoints por método HTTP (GET, POST, etc)
springdoc.swagger-ui.operationsSorter=method